languages:
   PHP: true
   JavaScript: false
exclude_paths:
- "tests/"
- "Core/Plugins"
- "docs/"
- "**.js"
engines:
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
  eslint:
    enabled: false
  csslint:
    enabled: false